### ISSUE TITLE
Поддержка групп

### ISSUE THREAD

**Issue by Goodsmileduck** [LibertyPaul/LostFilmUpdatesBot#12]
Добавляю в группу, шлю комманды а он мне в личные отправяет. Не тот chat_id я так понимаю используется.

**Comment by LibertyPaul** [comment]
Привет, спасибо за фидбэк.
На данный момент бот не умеет работать с группами. 
Я попробую продумать такой use-case.

**Comment by LibertyPaul** [comment]
Done. Will be deployed into prod after several days/weeks of testing.
